name: Auto Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Build
        run: dotnet publish TmlHjsonLinter.csproj -r linux-x64 -c Release -p:PublishSingleFile=true -o ./bin --artifacts-path ./temp

      - name: Create Tag
        id: create_tag
        run: |
          date=$(date +'%Y.%m.%d-%H.%M.%S')
          echo "tag=${date}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./bin/TmlHjsonLinter
          tag_name: ${{ steps.create_tag.outputs.tag }}
